### ISSUE TITLE
Create better example graphs

### ISSUE THREAD

**Issue by leonsterling** [MotivationalModelling/mm-local-editor#13]
Have sample data more systematised

**Comment by thomasjtHe** [comment]
The example graph layout should look like this:
![图片1](https://github.com/user-attachments/assets/c34a7cd9-ceb6-46a1-aea9-444c2444d77b)
Where Quality Goals and EMotional goals are rendered at top-left & right, Negative at the bottom, stakeholders below Emotional, on the same level as Functional Goals.
