### ISSUE TITLE
Improve Render Graph Layout

### ISSUE THREAD

**Issue by thomasjtHe** [MotivationalModelling/mm-local-editor#16]
3 New Requirements to be added to the graphWorker:
1. If there is no goals in the goal list, when switching to the render graph, a warning pops out and show the example graph
2. Text should be located in the middle of the bubble.
3. Move Show section 1 button on top of select colours.

**Comment by Hkarnen** [comment]
Also:
Having multiple non-functional goals
Moving positions: quality (TL), emotional (TR), concern (BR)

**Comment by Hkarnen** [comment]
The first point (warning) is done

**Comment by thomasjtHe** [comment]
Point 3 is also done but structure of the right side bar should be changed to fit the blank space.

**Comment by Hkarnen** [comment]
Point 2 is also done

**Comment by Hkarnen** [comment]
New point: warning at bottom right as a text (instead of alert) instead
