### ISSUE TITLE
GraphWorker: Functions and Buttons for Render & Export

### ISSUE THREAD

**Issue by frankwan41** [MotivationalModelling/mm-local-editor#8]
We need to implement the following functionalities:

A button to render the graph from a JSON file (hierarchy structure).
A button to export the graph as an image or XML file for further use.

Possible start [Here](https://github.com/MotivationalModelling/mm-local-editor/blob/29825dc5f015f81c7d2c55dbd84184ec8d590f4a/src/components/GraphRender.tsx#L1)

**Comment by Hkarnen** [comment]
Render graph from JSON file sort of done: can export and import as usual, and the graph is automatically rendered.
